### ISSUE TITLE
Special stages is broken

### ISSUE THREAD

**Issue by zal16** [usineur/rvm_soniccd#1]
I'm using the 2.0.0 mobile game version
The special stage's ground (mode 7 graphics) is missing.

**Comment by usineur** [comment]
2.0.0 ? Iphone (IPA) ? Android ?

Also, you don't you provide savestate...

**Comment by zal16** [comment]
I'm using the android version

**Comment by zal16** [comment]
O discovered My Data.rsdx is corrupted. Recopy then and the game runs normally
