### ISSUE TITLE
Volume control of music and sfx not working

### ISSUE THREAD

**Issue by zal16** [usineur/rvm_soniccd#2]
the sound settings are saved (you can see through the volume bars), but when you enter the game, you can perceive that the volumes are always at maximum.

**Comment by usineur** [comment]
Not implemented yet

**Comment by zal16** [comment]
didn't you implement or was it Sappharad?

**Comment by usineur** [comment]
The Switch is based on the engine made by Sappharad.
I only ported it to Nintendo Switch. And also provided a way to play FMV throught libmpv.

So what works on RVM engine should work on Switch. To my knowledges, this feature is not yet implemented.
