### ISSUE TITLE
game keeps running in the background

### ISSUE THREAD

**Issue by zal16** [usineur/rvm_soniccd#3]
when I press the home button on the console, the game continues to run in the background (you can see the game counter skipping numbers, after returning to the game, the music also advances, as if it were not paused).

would it be possible to implement some kind of "autopause" as a workaround?

**Comment by usineur** [comment]
Just tried, can't reproduce.

Tested with latest build, Iphone v3.0.6

**Comment by zal16** [comment]
do the following: open the game and start a stage, look at the counter and memorize its value, press the home button, wait for about 10 seconds, return to the game, you will notice that the game counter has advanced 10 seconds (even in background).

i tested with 2.0.0 android version (i'm not finding the iOS version)

**Comment by usineur** [comment]
Yes, I get it, and I can confirm that on resume, game counter and music are resumed properly on my device.

**Comment by zal16** [comment]
how are you running the game?

my CFW is SXOS 3.1.0, I created an nsp forwarder (to have access to full memory), but the same problem happens when I run through the hbmenu (pressing R in any game)

**Comment by zal16** [comment]
The problem is my fowarder, i created one to go directly to teh game and skip the process of opening hbmenu
